### ISSUE TITLE
example跑不通

### ISSUE THREAD

**Issue by brucelin-cn** [Zwlin98/moon#1]
example.go 能运行起来
moon.lua  我是用是skeynet的版本是1.7.0，但是被断开了，抓包看 返回了。 HTTP/1.1 400 Bad Request
Connection: close
是skynet 有版本限制？

运行环境：
linux x86

**Comment by brucelin-cn** [comment]
找到问题了 example 3345 已经有其它服务占用了

**Comment by Zwlin98** [comment]
更新了一下 README, 可以看看示例的 http 服务
